### ISSUE TITLE
pw is always incorrect

### ISSUE THREAD

**Issue by lori99-data** [mattwarkentin/fidelius#8]
I follow your instruction, but the pw is always incorrect.
I added my code and issue page below. Do you know how to correct this?

<img width="491" alt="Screen Shot 2022-05-12 at 6 50 22 PM" src="https://user-images.githubusercontent.com/56170047/168195414-e23a70e4-cdc1-449c-a6c5-92ce9b4a070d.png">

<img width="710" alt="Screen Shot 2022-05-12 at 6 50 16 PM" src="https://user-images.githubusercontent.com/56170047/168195437-b576ba81-a16a-4aaf-9ba3-3617a60de9fb.png">

**Comment by mattwarkentin** [comment]
Hi @lori99-data,

Sorry to hear that the package is not working as expected.

Could you let me know what web browser you are using? Could you also share the full content of the R Markdown document? I am unable to reproduce the issue.

**Comment by clementrx** [comment]
Hi ! I have the same issue, i tried with different browser (Safari, chrome, firefox...). I have generated a .html file from Quarto.
